- name: Install fonts arch
  tags:
    - fonts
  vars:
    - fonts:
      - name: Ubuntu
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Ubuntu.zip
      - name: Noto
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Noto.zip
      - name: FantasqueSansMono
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/FantasqueSansMono.zip


  block:
    - name: Ensure fonts folder exist
      ansible.builtin.file:
        path: ~/.fonts
        state: directory
        mode: '0755'

    - name: Download font
      with_items: "{{ fonts }}"
      ansible.builtin.unarchive:
        src: "{{ item.url }}"
        dest: ~/.fonts
        remote_src: yes

    - name: Install downloaded fonts
      ansible.builtin.shell: >
        fc-cache -fv
